// Markaziy ma'lumotlar ombori (server ulangandan keyin API ga o'tadi)
import { useState } from 'react'

export const initialGroups = [
  { id: 'inno',   name: 'Inno Texnopark', login: 'inno',   password: 'Inno@2026#kdr'   },
  { id: 'milliy', name: 'Milliy Offis',   login: 'milliy', password: 'Milliy@2026#kdr' },
]

export const initialEmployees = [
  { id:'00000014', name:'Urinboyev Sadriddin',       group:'inno',   lavozim:'' },
  { id:'00000016', name:'Abdunofiyev Suxbatjon',     group:'inno',   lavozim:'' },
  { id:'00000017', name:"Ne'matov Asadbek",          group:'inno',   lavozim:'' },
  { id:'00000021', name:'Toshmatov Shoxruh',         group:'inno',   lavozim:'' },
  { id:'00000022', name:'Maxamatov Xamidulla',       group:'inno',   lavozim:'' },
  { id:'00000024', name:'Abdujabbarov Abdumuxtor',   group:'inno',   lavozim:'' },
  { id:'00000025', name:'Yusupov Baxrom',            group:'inno',   lavozim:'' },
  { id:'00000026', name:'Atabayev Murodjon',         group:'inno',   lavozim:'' },
  { id:'00000028', name:'Torayev Mixritdin',         group:'inno',   lavozim:'' },
  { id:'00000029', name:'Ermatov Xamid',             group:'inno',   lavozim:'' },
  { id:'00000030', name:'Xaydarova Shaxnoza',        group:'inno',   lavozim:'' },
  { id:'00000031', name:'Darvisheva Nodira',         group:'inno',   lavozim:'' },
  { id:'00000032', name:'Yakubova Rano',             group:'inno',   lavozim:'' },
  { id:'00000099', name:'Doniyorov Ahror',           group:'inno',   lavozim:'' },
  { id:'00000100', name:'Sardor Madrimov',           group:'inno',   lavozim:'' },
  { id:'00000137', name:'Begzod Qodirov',            group:'inno',   lavozim:'' },
  { id:'00000142', name:'Shoxrux Asqaraliyev',       group:'inno',   lavozim:'' },
  { id:'00000143', name:'Salohiddinov Mahmud',       group:'inno',   lavozim:'' },
  { id:'00000147', name:'Sobirjon Boriyev',          group:'inno',   lavozim:'' },
  { id:'00000166', name:'Akbarova Dilsora',          group:'inno',   lavozim:'' },
  { id:'00000185', name:'Umid Buxgalter',            group:'inno',   lavozim:'' },
  { id:'00000259', name:'Buxgalter Nematjon',        group:'inno',   lavozim:'' },
  { id:'00000346', name:'Kamola Rasulova',           group:'inno',   lavozim:'' },
  { id:'00000381', name:'Nargiza Vazliyeva',         group:'inno',   lavozim:'' },
  { id:'00000401', name:'Sarimov Fahriddin',         group:'inno',   lavozim:'' },
  { id:'00000405', name:'Nodir Avezimbetov',         group:'inno',   lavozim:'' },
  { id:'00000415', name:'Boymatov Elbek',            group:'inno',   lavozim:'' },
  { id:'00000425', name:'Isayeva Feruza',            group:'inno',   lavozim:'' },
  { id:'00000426', name:'Muzaffar Eshonqulov',       group:'inno',   lavozim:'' },
  { id:'00000500', name:'Akbarxon Sobirxonov',       group:'inno',   lavozim:'' },
  { id:'00000009', name:'Zafar Asrorov',             group:'milliy', lavozim:'' },
  { id:'00000010', name:'Erkin Davirov',             group:'milliy', lavozim:'' },
  { id:'00000013', name:'Allabergenov Shokhrukhbek', group:'milliy', lavozim:'' },
  { id:'00000019', name:'Otaxonov Obidxon',          group:'milliy', lavozim:'' },
  { id:'00000090', name:'Baxtiyor Islomov',          group:'milliy', lavozim:'' },
  { id:'00000149', name:'Aziz Akramov',              group:'milliy', lavozim:'' },
  { id:'00000154', name:'Kenjayev Nuriddin',         group:'milliy', lavozim:'' },
  { id:'00000414', name:'Yaqubov Oktam',             group:'milliy', lavozim:'' },
  { id:'00000422', name:'Akbarali Yakubov',          group:'milliy', lavozim:'' },
  { id:'00000423', name:'Sanjarbek Usmonov',         group:'milliy', lavozim:'' },
  { id:'00000424', name:'Shaxobiddin Shamsiyev',     group:'milliy', lavozim:'' },
  { id:'00000427', name:'Malik Rashidov',            group:'milliy', lavozim:'' },
  { id:'00000434', name:'Otaxojayeva Madina',        group:'milliy', lavozim:'' },
  { id:'00000436', name:'Sultonova Aziza',           group:'milliy', lavozim:'' },
  { id:'00000437', name:'Saydivaliyeva Saida',       group:'milliy', lavozim:'' },
  { id:'00000438', name:'Pulatova Shaxnoza',         group:'milliy', lavozim:'' },
  { id:'00000456', name:'Sadirov Jamoliddin',        group:'milliy', lavozim:'' },
  { id:'00000466', name:'Ermataliyev Mehmonali',     group:'milliy', lavozim:'' },
  { id:'00000467', name:'Madaminova Shaxnoza',       group:'milliy', lavozim:'' },
  { id:'00000473', name:'Ibragimova Feruza',         group:'milliy', lavozim:'' },
  { id:'00000490', name:'Qurbonov Behzod',           group:'milliy', lavozim:'' },
  { id:'00000502', name:'Niyozov Azizjon',           group:'milliy', lavozim:'' },
  { id:'00000503', name:'Mustafoyev Eldor',          group:'milliy', lavozim:'' },
  { id:'00000505', name:'Qodirov Shoxruh',           group:'milliy', lavozim:'' },
]
